### PR TITLE
O11y 922 handle no users in schedule case

### PR DESCRIPTION
**Pull request by equinsuocha**

### CODE REVIEW

**Comment by pipedrive-bot-eventsink** [comment]
### Main branch dependencies
[snyk vulnerabilities](https://app.snyk.io/org/infra-6or/project/400b8815-503e-4f8f-955b-208588583c45)

**Review by karlmartink — APPROVED** [review]

**Comment by pipedrive-bot-dora** [comment]
## Neodora Analysis ⚠


<details><summary><strong> ⚠ Bad use of status</strong></summary>
<br/>

**Message:** The `status` property must be one of: `unreleased`, `released`, `archived`
**Repository file:** [repository.json](https://github.com/pipedrive/slack-groups/tree/cfaedb718f662e51c8d0fdc2edc87d311affc2bc/repository.json)

<table>
<thead>
	<tr>
			<th>Actual status</th>
	</tr>
</thead>
<tbody>
		<tr>
				<td><code>Not found</code></td>
		</tr>
</tbody>
</table>


🔍 [How to fix it](https://neodora.pipedrive.tools/rules/allowedStatuses)
<br/>
</details>


Commit [`cfaedb7`](https://github.com/pipedrive/slack-groups/commit/cfaedb718f662e51c8d0fdc2edc87d311affc2bc/)  Job [`53195`](https://jenkins.pipedrive.tools/job/neodora/53195/)

**Comment by pipedrive-bot-dora** [comment]
## Neodora Analysis ✅


Commit [`aa1102f`](https://github.com/pipedrive/slack-groups/commit/aa1102fb3c79a5665ec9940debfe60846d8ec027/)  Job [`53199`](https://jenkins.pipedrive.tools/job/neodora/53199/)

**Comment by pipedrive-bot-dora** [comment]
## Neodora Analysis ✅


Commit [`aa1102f`](https://github.com/pipedrive/slack-groups/commit/aa1102fb3c79a5665ec9940debfe60846d8ec027/)  Job [`53210`](https://jenkins.pipedrive.tools/job/neodora/53210/)

**Review by karlmartink — APPROVED** [review]

**Comment by pipedrive-bot-dora** [comment]
## Neodora Analysis ✅


Commit [`aa1102f`](https://github.com/pipedrive/slack-groups/commit/aa1102fb3c79a5665ec9940debfe60846d8ec027/)  Job [`53235`](https://jenkins.pipedrive.tools/job/neodora/53235/)

**Pull request merged**
